# GitHub Actions workflow: Auto-tag releases based on version in espTicker32.cpp

name: Auto Tag Release

# Run this workflow only when pushing to the main branch
on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract version from espTicker32.cpp
      # Expected format: const char* PROG_VERSION = "v1.2.3";
      - name: Get version from espTicker32.cpp
        id: get_version
        run: |
          VERSION=$(grep 'const char\* PROG_VERSION' src/espTicker32.cpp | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Step 3: Fetch all existing Git tags from the repo
      - name: Fetch all tags
        run: git fetch --tags

      # Step 4: Find the latest semantic version tag (supports v-prefixed versions like "v1.2.3")
      - name: Get latest semver tag
        id: latest_tag
        run: |
          # This finds the latest tag that matches semver format, optionally prefixed with 'v'
          LATEST=$(git tag --sort=-v:refname | grep -E '^v?([0-9]+\.){2}[0-9]+$' | head -n 1 || true)
          echo "Latest existing tag: $LATEST"
          echo "LATEST=$LATEST" >> $GITHUB_OUTPUT

      # Step 5: Compare the current version with the latest tag and determine whether to create a new tag
      - name: Compare version
        id: compare_version
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          LATEST="${{ steps.latest_tag.outputs.LATEST }}"

          echo "Comparing VERSION: $VERSION with LATEST: $LATEST"

          # Strip 'v' prefix if it exists for accurate numeric comparison
          STRIPPED_VERSION="${VERSION#v}"
          STRIPPED_LATEST="${LATEST#v}"

          if [ -z "$LATEST" ]; then
            echo "No existing tag found. Proceeding to tag."
            echo "PROCEED=true" >> $GITHUB_ENV
          elif [ "$STRIPPED_VERSION" = "$STRIPPED_LATEST" ]; then
            echo "::warning::Version $VERSION already exists. Skipping tagging."
            echo "PROCEED=false" >> $GITHUB_ENV
          elif [ "$(printf '%s\n' "$STRIPPED_LATEST" "$STRIPPED_VERSION" | sort -V | head -n1)" != "$STRIPPED_LATEST" ]; then
            echo "::warning::Version $VERSION is not greater than $LATEST. Skipping tagging."
            echo "PROCEED=false" >> $GITHUB_ENV
          else
            echo "Version $VERSION is newer than $LATEST. Proceeding to tag."
            echo "PROCEED=true" >> $GITHUB_ENV
          fi

      # Step 6: Create and push a new tag if the version is valid and newer
      - name: Create and push tag
        if: env.PROCEED == 'true'
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "$VERSION"
          git push origin "$VERSION"
          