name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from espTicker32.cpp
        id: get_version
        run: |
          VERSION=$(grep 'const char\* ESPTICKER32_VERSION' src/espTicker32.cpp | sed -E 's/.*"([^"]+)".*/\1/')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest semver tag
        id: latest_tag
        run: |
          LATEST=$(git tag --sort=-v:refname | grep -E '^([0-9]+\.){2}[0-9]+$' | head -n 1 || echo "0.0.0")
          echo "LATEST=$LATEST"
          echo "LATEST=$LATEST" >> $GITHUB_OUTPUT

      - name: Debug version info
        run: |
          echo "DEBUG: VERSION from get_version: ${{ steps.get_version.outputs.VERSION }}"
          echo "DEBUG: LATEST from latest_tag: ${{ steps.latest_tag.outputs.LATEST }}"

      - name: Compare version
        id: compare_version
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          LATEST="${{ steps.latest_tag.outputs.LATEST }}"

          echo "Comparing VERSION: $VERSION with LATEST: $LATEST"

          if [ "$VERSION" = "$LATEST" ]; then
            echo "::warning::Version $VERSION already exists. Skipping tagging."
            echo "PROCEED=false" >> $GITHUB_ENV
          elif [ "$(printf '%s\n' "$LATEST" "$VERSION" | sort -V | head -n1)" = "$LATEST" ]; then
            echo "Version $VERSION is newer than $LATEST. Proceeding to tag."
            echo "PROCEED=true" >> $GITHUB_ENV
          else
            echo "::warning::Version $VERSION is not greater than existing tag $LATEST. Skipping tagging."
            echo "PROCEED=false" >> $GITHUB_ENV

      - name: Create and push tag
        if: env.PROCEED == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "${{ steps.get_version.outputs.VERSION }}"
          git push origin "${{ steps.get_version.outputs.VERSION }}"
          